# Featuring

**Import** data from "data/cleaned.csv"

**Export** to "data/featured.csv"

In [6]:
# Setup

import numpy as np
import pandas as pd

from pkg import utils
from pkg import feature

In [7]:
# Importing data

path = utils.get_parents() + r"/data/cleaned.csv"

df = pd.read_csv(path, index_col=0)
df.head()

,dominance_simpson,12DICHLORETHDEG-PWY,AEROBACTINSYN-PWY,ALLANTOINDEG-PWY,CRNFORCAT-PWY,DENITRIFICATION-PWY,DHGLUCONATE-PYR-CAT-PWY,DTDPRHAMSYN-PWY,METH-ACETATE-PWY,P108-PWY,...,bisq_9_mins_t1,bisq_sleep_prob_t1,ebia_tot_t1,educationLevelAhmedNum_t1,a10_t1,bmi_pregest_t1,ibq_reg_t1,ibq_soot_t1,ibq_dura_t1,bayley_3_t1
7,0.136112,0.0,0.000000,7.676483,0.0,0.000000,0.0,4395.178167,0.0,171.940413,...,239.0,1.0,0.0,16.0,3.0,32.36855,4.654762,5.857143,2.333333,100.0
8,0.451324,0.0,0.000000,14.984719,0.0,320.494755,0.0,4478.753445,0.0,43.380158,...,60.0,0.0,0.0,20.0,1.0,20.79673,4.626190,4.428571,3.600000,75.0
14,0.281675,0.0,209.593817,0.000000,0.0,0.000000,0.0,2755.525229,0.0,0.000000,...,30.0,0.0,0.0,16.0,1.0,21.36752,5.872024,5.571429,4.750000,95.0
24,0.945041,0.0,0.000000,0.000000,0.0,26.374059,0.0,2725.705501,0.0,50.368350,...,30.0,0.0,2.0,16.0,5.0,38.51406,5.684524,4.571429,5.000000,115.0
26,0.338783,0.0,0.000000,0.000000,0.0,0.000000,0.0,725.879153,0.0,0.000000,...,120.0,1.0,0.0,12.0,2.0,22.94812,5.369048,6.142857,3.000000,105.0

In [8]:
X_list = df.columns[1:-5]
y_list = df.columns[-1]

X = df[X_list]
y = df[y_list]

In [9]:
featured = pd.concat([y,X],axis=1)
featured.head()

,bayley_3_t1,12DICHLORETHDEG-PWY,AEROBACTINSYN-PWY,ALLANTOINDEG-PWY,CRNFORCAT-PWY,DENITRIFICATION-PWY,DHGLUCONATE-PYR-CAT-PWY,DTDPRHAMSYN-PWY,METH-ACETATE-PWY,P108-PWY,...,delivery_mode,chaos_tot_t1,epds_2c_t1,bisq_3_mins_t1,bisq_4_mins_t1,bisq_9_mins_t1,bisq_sleep_prob_t1,ebia_tot_t1,educationLevelAhmedNum_t1,a10_t1
7,100.0,0.0,0.000000,7.676483,0.0,0.000000,0.0,4395.178167,0.0,171.940413,...,1.0,4.0,0.0,480.0,540.0,239.0,1.0,0.0,16.0,3.0
8,75.0,0.0,0.000000,14.984719,0.0,320.494755,0.0,4478.753445,0.0,43.380158,...,1.0,1.0,0.0,570.0,240.0,60.0,0.0,0.0,20.0,1.0
14,95.0,0.0,209.593817,0.000000,0.0,0.000000,0.0,2755.525229,0.0,0.000000,...,1.0,2.0,0.0,720.0,90.0,30.0,0.0,0.0,16.0,1.0
24,115.0,0.0,0.000000,0.000000,0.0,26.374059,0.0,2725.705501,0.0,50.368350,...,3.0,0.0,0.0,600.0,360.0,30.0,0.0,2.0,16.0,5.0
26,105.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,725.879153,0.0,0.000000,...,1.0,7.0,0.0,420.0,480.0,120.0,1.0,0.0,12.0,2.0

In [10]:
# Exporting data

featured = featured.dropna(axis=0)

run_save = False
if not run_save:
  utils.save_df(featured, "featured.csv")
  run_save = True

csv file saved on:  c:\Users\ptons\Code\repositories\brainwise\data\featured.csv